services:
  spring-app:
    build: .
    container_name: pilter-BE
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod,secret
      - SPRING_DATASOURCE_URL=${REAL_DB_URL_PROD}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME_PROD}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_PROD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro