version: '3.8'
services:
  spring-app:
    build: .
    container_name: pilter-BE
    ports:
      - "8080:8080"
    environment:
      # 😎 진짜 RDS 정보는 이미 secret.yml에 있으니, 여기서는 프로필을 활성화하라는 신호만 줍니다!
      - SPRING_PROFILES_ACTIVE=prod,secret
    restart: always