spring:
  profiles:
    active: prod # 개발환경 dev
    include: secret # 민감정보 secret 파일

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
