spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  config:
    activate:
      on-profile: prod
    profiles:
      include: secret

  datasource:
    url: ${SECRET.REAL_DB_URL_PROD}
    username: ${SECRET.DB_USERNAME_PROD}
    password: ${SECRET.DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create 사용하고 푸쉬 후 update로 바꿔둘 것.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  packages-to-scan: com.ll.projectLimC

cors:
  allowed-origin: https://pilter.co.kr

#spring:
#  config:
#    activate:
#      on-profile: prod
#    profiles:
#      # prod 프로필이 켜질 때, dev에 적힌 H2 DB 설정도 함께 묶어서 가져오라는 뜻!
#      # include: dev
#      include: secret
#
#  datasource:
#    url: ${SECRET.REAL_DB_URL_PROD}
#    username: ${SECRET.DB_USERNAME_PROD}
#    password: ${SECRET.DB_PASSWORD_PROD}
#
#  jpa:
#    # ddl-auto: update # 운영 환경 안전을 위해 validate 유지
#    properties:
#      hibernate:
#        hbm2ddl.auto: update
#        format_sql: false
#        show_sql: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect