spring:
  profiles:
    active: prod # 개발환경 dev
    include: secret # 민감정보 secret 파일

server:
  port: 8080

  tomcat:
    # 톰캣 기반 임시 디렉토리 경로를 프로젝트 내부의 빌드 폴더 등으로 우회시킴
    basedir: ./.tomcat

  servlet:
    context-path: /api

  forward-headers-strategy: framework

springdoc:

  swagger-ui:
    # 접속 경로를 http://localhost:8080/api/swagger-ui.html 로 단순화
    path: /swagger-ui.html
    # API 태그(컨트롤러 이름)와 메서드(GET, POST 등)들을 알파벳 순서로 이쁘게 정렬
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    # 스웨거가 API를 분석한 json 원본 데이터가 나오는 경로
    path: /api-docs
#  packages-to-scan: com.ll.projectLimC

cors:
  allowed-origin: http://localhost:3000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: "pilter-uploaded-bucket"
    region:
      static: "ap-northeast-2"