spring:
  config:
    activate:
      on-profile: dev

    datasource:
    driver-class-name: org.postgresql.Driver # org.h2.Driver #
    url: ${SECRET.DB_URL_DEV}
    # jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: ${SECRET.DB_USERNAME_DEV} # sa
    password: ${SECRET.DB_PASSWORD_DEV} #

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none # 로컬에서는 테이블이 자동 수정되도록 편하게 설정
    properties:
      hibernate:
        format_sql: true
        show_sql: true

        # PostgreSQL에 최적화된 방언(Dialect) 설정 - 스프링 부트 3.x부터는 생략해도 자동 감지, 명시하면 정확해지기에 입력
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  packages-to-scan: com.ll.projectLimC

cors:
  allowed-origin: http://localhost:3000